import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {sqlite} from '../scripts/sqlite-adapter.mjs';import {handle} from '../src/worker.mjs';
const migration=await readFile(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8');
const gradeMigration=await readFile(new URL('../migrations/0003_webhorario_lessons.sql',import.meta.url),'utf8');
const planningMigration=await readFile(new URL('../migrations/0002_substitution_planning.sql',import.meta.url),'utf8');
const responsibleMigration=await readFile(new URL('../migrations/0004_reservation_responsible.sql',import.meta.url),'utf8');
function setup(){const DB=sqlite();DB.exec(migration+planningMigration+gradeMigration+responsibleMigration);DB.exec("INSERT INTO users VALUES('director@prof.pmf.sc.gov.br','Direção','direction',1),('one@prof.pmf.sc.gov.br','Professor um','teacher',1),('two@prof.pmf.sc.gov.br','Professor dois','teacher',1),('inactive@prof.pmf.sc.gov.br','Inativo','teacher',0)");return {DB,ASSETS:{fetch:async()=>new Response('<html>teste</html>')}}}
const send=async(env,path,method='GET',data,email='director@prof.pmf.sc.gov.br',origin='https://school.example')=>{if(['PATCH','DELETE'].includes(method)&&data&&data.version===undefined){const [kind,id]=path.split('/');const table=kind.replace('fixed-occupancy','fixed_occupancy');const row=await env.DB.prepare('SELECT version FROM '+table+' WHERE id=?').bind(id).first();data={...data,version:row?.version||1}}const r=await handle(new Request('https://school.example/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json'},body:method==='GET'?undefined:JSON.stringify(data)}),env,async()=>email);return {status:r.status,body:await r.json()}};
const reservation={space:'Biblioteca',date:'2026-10-05',start:'09:00',end:'10:00',purpose:'Leitura fictícia',responsible:'Responsável fictício'};
const taskData={title:'Conferir calendário',due:'2026-10-05',owner:'one@prof.pmf.sc.gov.br',restricted:false};
test('reservation responsible is required, persists and never changes creator permissions',async()=>{
 const e=setup();for(const responsible of [undefined,'','   ',42,'x'.repeat(251)])assert.equal((await send(e,'reservations','POST',{...reservation,responsible})).status,400);
 const created=await send(e,'reservations','POST',{...reservation,responsible:'  Pessoa indicada  '},'one@prof.pmf.sc.gov.br');assert.equal(created.status,201);
 let row=(await send(e,'reservations')).body[0];assert.equal(row.responsible,'Pessoa indicada');assert.equal(row.owner,'one@prof.pmf.sc.gov.br');
 assert.equal((await send(e,'reservations/'+created.body.id,'PATCH',{...reservation,responsible:'Outra pessoa',edit:true},'two@prof.pmf.sc.gov.br')).status,403);
 assert.equal((await send(e,'reservations/'+created.body.id,'PATCH',{...reservation,responsible:'  Outra pessoa  ',edit:true},'one@prof.pmf.sc.gov.br')).status,200);
 row=(await send(e,'reservations')).body[0];assert.equal(row.responsible,'Outra pessoa');assert.equal(row.owner,'one@prof.pmf.sc.gov.br');
});
test('responsible migration preserves existing reservations with their creator name',async()=>{
 const DB=sqlite();DB.exec(migration);DB.exec("INSERT INTO users VALUES('legacy@prof.pmf.sc.gov.br','Pessoa anterior','teacher',1); INSERT INTO reservations(id,space,date,start,end,owner,purpose) VALUES('legacy','Biblioteca','2026-10-05','09:00','10:00','legacy@prof.pmf.sc.gov.br','Leitura')");DB.exec(responsibleMigration);
 const row=await DB.prepare('SELECT * FROM reservations').first();assert.equal(row.responsible,'Pessoa anterior');assert.equal(row.id,'legacy');assert.equal(row.version,1);
});

test('multiple absence dates are atomic, enforce weekly capacity and roll back audit',async()=>{
 const e=setup();const auxiliary='aux-example-ana';
 const absence={dates:['2026-10-04','2026-10-05','2026-10-06'],start:'08:00',end:'08:45',class:'Turma fictícia',teacher:'Professor fictício',auxiliary};
 const created=await send(e,'substitutions','POST',absence);assert.equal(created.status,201);assert.equal(created.body.count,3);
 const rows=(await send(e,'substitutions')).body;assert.deepEqual(rows.map(x=>x.week),['2026-09-28','2026-10-05','2026-10-05']);assert.ok(rows.every(x=>x.auxiliary===auxiliary));
 const report=(await send(e,'auxiliaries/weekly?date=2026-10-06')).body;assert.equal(report.week,'2026-10-05');assert.equal(report.auxiliaries.find(x=>x.id===auxiliary).scheduled,2);
 const auditCount=(await send(e,'audit')).body.length;
 const conflicting=await send(e,'substitutions','POST',{...absence,dates:['2026-10-07','2026-10-06']});assert.equal(conflicting.status,409);
 assert.equal((await send(e,'substitutions')).body.length,3);assert.equal((await send(e,'audit')).body.length,auditCount);
 assert.equal((await send(e,'substitutions','POST',{...absence,dates:['2026-10-08','2026-10-08']})).status,400);
 assert.equal((await send(e,'substitutions','POST',{...absence,dates:['2026-02-30']})).status,400);
 assert.equal((await send(e,'substitutions','POST',absence,'one@prof.pmf.sc.gov.br')).status,403);
 e.DB.exec("UPDATE settings SET value=3 WHERE key='auxiliary_weekly_limit'");
 const overflow=await send(e,'substitutions','POST',{...absence,dates:['2026-10-07','2026-10-08']});assert.equal(overflow.status,409);
 assert.equal((await send(e,'substitutions')).body.length,3);assert.equal((await send(e,'audit')).body.length,auditCount);
 const parallel=await send(e,'substitutions','POST',{...absence,dates:['2026-10-07','2026-10-05'],class:'Outra turma'});assert.equal(parallel.status,409);
 assert.equal((await send(e,'substitutions')).body.length,3);
 assert.equal((await send(e,'auxiliaries/weekly?date=2026-02-30')).status,400);
});

test('realized lessons have explicit status, version checks and preserved auxiliary history',async()=>{
 const e=setup(),auxiliary='aux-example-ana';
 const absence={date:'2000-01-03',start:'08:00',end:'08:45',class:'Turma fictícia',teacher:'Professor fictício',auxiliary};
 const created=await send(e,'substitutions','POST',absence);assert.equal(created.status,201);const path='substitutions/'+created.body.id;
 assert.equal((await send(e,path,'PATCH',{completed:true},'one@prof.pmf.sc.gov.br')).status,403);
 assert.equal((await send(e,path,'PATCH',{completed:true,version:1})).status,200);
 assert.equal((await send(e,path,'PATCH',{completed:false,version:1})).status,409);
 assert.equal((await send(e,path,'PATCH',{auxiliary:null})).status,409);
 const report=(await send(e,'auxiliaries/weekly?date=2000-01-04')).body;
 const row=report.auxiliaries.find(x=>x.id===auxiliary);assert.equal(row.completed,1);assert.equal(row.scheduled,0);assert.equal(row.total,1);assert.equal(row.remaining,31);
 assert.equal((await send(e,'auxiliaries/'+auxiliary,'DELETE',{})).status,200);
 const historical=(await send(e,'auxiliaries/weekly?date=2000-01-04')).body.auxiliaries.find(x=>x.id===auxiliary);assert.equal(historical.active,0);assert.equal(historical.completed,1);
 assert.equal((await send(e,path,'PATCH',{completed:false})).status,200);
 assert.equal((await send(e,path,'PATCH',{auxiliary:null})).status,200);
 const future=await send(e,'substitutions','POST',{...absence,date:'2099-10-05',auxiliary:'aux-example-beatriz'});
 assert.equal((await send(e,'substitutions/'+future.body.id,'PATCH',{completed:true})).status,400);
 const pending=await send(e,'substitutions','POST',{...absence,date:'2000-01-04',auxiliary:null});
 assert.equal((await send(e,'substitutions/'+pending.body.id,'PATCH',{completed:true})).status,400);
});
test('fail closed: missing DB, JWT, nominal authorization and inactive users',async()=>{assert.equal((await send({},'tasks')).status,503);const e=setup();assert.equal((await send(e,'tasks','GET',undefined,null)).status,401);assert.equal((await send(e,'tasks','GET',undefined,'unknown@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'tasks','GET',undefined,'inactive@prof.pmf.sc.gov.br')).status,403);const real=await handle(new Request('https://school.example/api/tasks',{headers:{'Cf-Access-Authenticated-User-Email':'director@prof.pmf.sc.gov.br'}}),e);assert.equal(real.status,401);});
test('reservations: persistent, atomic overlap, adjacency, validation, ownership cancellation',async()=>{const e=setup();const a=await send(e,'reservations','POST',reservation,'one@prof.pmf.sc.gov.br');assert.equal(a.status,201);assert.equal((await send(e,'reservations')).body.length,1);assert.equal((await send(e,'reservations','POST',reservation)).status,409);assert.equal((await send(e,'reservations','POST',{...reservation,start:'10:00',end:'11:00'})).status,201);assert.equal((await send(e,'reservations','POST',{...reservation,date:'2026-02-30'})).status,400);assert.equal((await send(e,'reservations','POST',{...reservation,start:'25:00'})).status,400);assert.equal((await send(e,'reservations/'+a.body.id,'DELETE',{},'two@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'reservations/'+a.body.id,'DELETE',{},'one@prof.pmf.sc.gov.br')).status,200)});
test('tasks: restricted filtering, delegated owner and updates enforced by server',async()=>{const e=setup();assert.equal((await send(e,'tasks','POST',{...taskData,restricted:true},'one@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'tasks','POST',taskData,'two@prof.pmf.sc.gov.br')).status,403);const t=await send(e,'tasks','POST',{...taskData,restricted:true});assert.equal(t.status,201);assert.equal((await send(e,'tasks','GET',undefined,'two@prof.pmf.sc.gov.br')).body.length,0);assert.equal((await send(e,'tasks','GET',undefined,'one@prof.pmf.sc.gov.br')).body.length,1);assert.equal((await send(e,'tasks/'+t.body.id,'PATCH',{status:'Concluída'},'two@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'tasks/'+t.body.id,'PATCH',{status:'Concluída'},'one@prof.pmf.sc.gov.br')).status,200);assert.equal((await send(e,'tasks')).body[0].status,'Concluída');assert.equal((await send(e,'tasks/'+t.body.id,'PATCH',{status:'arbitrary'})).status,400)});
test('CSRF rejects absent and foreign origins',async()=>{const e=setup();assert.equal((await send(e,'reservations','POST',reservation,'director@prof.pmf.sc.gov.br','https://evil.example')).status,403);assert.equal((await send(e,'reservations','POST',reservation,'director@prof.pmf.sc.gov.br','null')).status,403)});
test('xerox: own requests, approval role and ordered transitions',async()=>{const e=setup();const x=await send(e,'xerox','POST',{title:'Folha fictícia',copies:30,deadline:'2026-10-05'},'one@prof.pmf.sc.gov.br');assert.equal(x.status,201);assert.equal((await send(e,'xerox','GET',undefined,'two@prof.pmf.sc.gov.br')).body.length,0);assert.equal((await send(e,'xerox/'+x.body.id,'PATCH',{status:'Aprovado'},'one@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'xerox/'+x.body.id,'PATCH',{status:'Concluído'})).status,400);for(const status of ['Aprovado','Em produção','Concluído'])assert.equal((await send(e,'xerox/'+x.body.id,'PATCH',{status})).status,200);assert.equal((await send(e,'xerox','POST',{title:'x',copies:-1,deadline:'2026-10-05'})).status,400)});
test('minutes/calendar: only direction writes, teacher reads, malformed dates rejected',async()=>{const e=setup();const minute={title:'Reunião fictícia',date:'2026-10-05',participants:'Equipe fictícia',decisions:'Conferir calendário'};assert.equal((await send(e,'minutes','POST',minute,'one@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'minutes','POST',minute)).status,201);assert.equal((await send(e,'minutes','GET',undefined,'one@prof.pmf.sc.gov.br')).body.length,1);assert.equal((await send(e,'events','POST',{title:'Reunião',date:'2026-10-05',type:'Reunião'})).status,201);assert.equal((await send(e,'events','POST',{title:'Reunião',date:'2026-13-05',type:'Reunião'})).status,400);assert.equal((await send(e,'students')).status,404)});
test('substitutions: per-week capacity, overlapping assignment, direction only',async()=>{const e=setup();const a=await send(e,'auxiliaries','POST',{name:'Auxiliar fictícia'});const sub={date:'2026-10-05',start:'08:00',end:'08:45',class:'Turma fictícia',teacher:'Professor fictício'};assert.equal((await send(e,'substitutions','POST',sub,'one@prof.pmf.sc.gov.br')).status,403);const x=await send(e,'substitutions','POST',sub);assert.equal((await send(e,'substitutions/'+x.body.id,'PATCH',{auxiliary:a.body.id})).status,200);const overlap=await send(e,'substitutions','POST',{...sub,class:'Outra turma'});assert.equal((await send(e,'substitutions/'+overlap.body.id,'PATCH',{auxiliary:a.body.id})).status,409);for(let n=1;n<32;n++){const start=String(Math.floor(n/2)+8).padStart(2,'0')+':'+(n%2?'30':'00');const end=String(Math.floor(n/2)+8).padStart(2,'0')+':'+(n%2?'59':'29');const y=await send(e,'substitutions','POST',{...sub,date:'2026-10-06',start,end,class:'Turma '+n});assert.equal((await send(e,'substitutions/'+y.body.id,'PATCH',{auxiliary:a.body.id})).status,200)}const excess=await send(e,'substitutions','POST',{...sub,date:'2026-10-07',class:'Excesso'});assert.equal((await send(e,'substitutions/'+excess.body.id,'PATCH',{auxiliary:a.body.id})).status,409)});
test('assets require auth and enforce no-store/CSP',async()=>{const e=setup();const r=await handle(new Request('https://school.example/'),e,async()=> 'one@prof.pmf.sc.gov.br');assert.equal(r.status,200);assert.match(r.headers.get('Content-Security-Policy'),/script-src 'self'/);assert.equal(r.headers.get('Cache-Control'),'no-store')});
test('database outage returns safe 503 without throwing',async()=>{const e={DB:{prepare(){throw Error('private database details')}}};const r=await send(e,'tasks');assert.equal(r.status,503);assert.equal(JSON.stringify(r.body).includes('private'),false)});
test('xerox compare-and-swap detects competing update and requester can resubmit adjustments',async()=>{const e=setup();const x=await send(e,'xerox','POST',{title:'Material',copies:10,deadline:'2026-10-05'},'one@prof.pmf.sc.gov.br');await send(e,'xerox/'+x.body.id,'PATCH',{status:'Devolvido para ajustes'});assert.equal((await send(e,'xerox/'+x.body.id,'PATCH',{resubmit:true,title:'Corrigido',copies:12,deadline:'2026-10-06'},'two@prof.pmf.sc.gov.br')).status,403);assert.equal((await send(e,'xerox/'+x.body.id,'PATCH',{resubmit:true,title:'Corrigido',copies:12,deadline:'2026-10-06'},'one@prof.pmf.sc.gov.br')).status,200);const base=e.DB;const race={...e,DB:{batch:base.batch,prepare(sql){if(sql.startsWith('UPDATE xerox SET status=')){base.prepare('UPDATE xerox SET status=? WHERE id=?').bind('Recusado',x.body.id).run();}return base.prepare(sql)}}};assert.equal((await send(race,'xerox/'+x.body.id,'PATCH',{status:'Aprovado'})).status,409);assert.equal((await send(e,'xerox')).body[0].status,'Recusado')});
test('CRUD roundtrips for every module, stale versions and permissions',async()=>{const e=setup();const fixtures=[['reservations',reservation,{...reservation,purpose:'Editada'}],['tasks',taskData,{...taskData,title:'Editada'}],['auxiliaries',{name:'Auxiliar'}, {name:'Auxiliar editada'}],['substitutions',{date:'2026-10-05',start:'08:00',end:'08:45',class:'Turma A',teacher:'Prof A'},{date:'2026-10-05',start:'09:00',end:'09:45',class:'Turma A',teacher:'Prof B'}],['xerox',{title:'Material',copies:10,deadline:'2026-10-05'},{title:'Editado',copies:20,deadline:'2026-10-06'}],['minutes',{title:'Ata',date:'2026-10-05',participants:'Equipe',decisions:'Pauta'},{title:'Ata editada',date:'2026-10-06',participants:'Equipe',decisions:'Decisão'}],['events',{title:'Evento',date:'2026-10-05',type:'Reunião'},{title:'Evento editado',date:'2026-10-06',type:'Dia letivo'}],['fixed-occupancy',{space:'Quadra coberta',weekday:1,start:'10:00',end:'11:00',from_date:'2026-10-05',to_date:'2026-12-01',purpose:'Aula'},{space:'Quadra coberta',weekday:2,start:'10:00',end:'11:00',from_date:'2026-10-05',to_date:'2026-12-01',purpose:'Aula editada'}]];for(const [kind,create,edit]of fixtures){const x=await send(e,kind,'POST',create);assert.equal(x.status,201,kind);const id=x.body.id;assert.equal((await send(e,kind+'/'+id,'PATCH',{...edit,edit:true,version:1},'two@prof.pmf.sc.gov.br')).status,403,kind+' role');assert.equal((await send(e,kind+'/'+id,'PATCH',{...edit,edit:true,version:1})).status,200,kind+' edit');assert.equal((await send(e,kind+'/'+id,'PATCH',{...edit,edit:true,version:1})).status,409,kind+' stale');assert.equal((await send(e,kind+'/'+id,'DELETE',{version:2})).status,200,kind+' delete')}const audit=await send(e,'audit');assert.ok(audit.body.length>=24);assert.equal((await send(e,'audit','GET',undefined,'one@prof.pmf.sc.gov.br')).status,403);assert.equal(JSON.stringify(audit.body).includes('Decisão'),false)});
test('fixed occupancy atomically blocks one-off reservations and edits in both directions',async()=>{const e=setup();const fixed={space:'Biblioteca',weekday:1,start:'09:00',end:'10:00',from_date:'2026-10-05',to_date:'2026-12-01',purpose:'Aula fixa'};assert.equal((await send(e,'fixed-occupancy','POST',fixed,'one@prof.pmf.sc.gov.br')).status,403);const f=await send(e,'fixed-occupancy','POST',fixed);assert.equal(f.status,201);assert.equal((await send(e,'reservations','POST',reservation)).status,409);assert.equal((await send(e,'fixed-occupancy','POST',fixed)).status,409);const b=await send(e,'reservations','POST',{...reservation,start:'10:00',end:'11:00'});assert.equal(b.status,201);assert.equal((await send(e,'reservations/'+b.body.id,'PATCH',{...reservation,edit:true})).status,409);assert.equal((await send(e,'fixed-occupancy/'+f.body.id,'PATCH',{...fixed,start:'10:00',end:'11:00',edit:true})).status,409);assert.equal((await send(e,'audit')).body.length,2,'failed writes produce no audit rows')});
test('transactional audit rolls back business mutation when audit cannot be written',async()=>{const e=setup();e.DB.exec('DROP TABLE audit');assert.equal((await send(e,'reservations','POST',reservation)).status,503);assert.equal((await send(e,'reservations')).body.length,0)});
test('simultaneous competing reservations result in one committed write and one conflict',async()=>{const e=setup();const results=await Promise.all([send(e,'reservations','POST',reservation),send(e,'reservations','POST',reservation)]);assert.deepEqual(results.map(x=>x.status).sort(),[201,409]);assert.equal((await send(e,'reservations')).body.length,1);assert.equal((await send(e,'audit')).body.length,1)});
test('item mutations reject malformed routes without bypassing version checks',async()=>{const e=setup();const b=await send(e,'reservations','POST',reservation);for(const suffix of ['/extra','/','//']){const r=await send(e,'reservations/'+b.body.id+suffix,'DELETE',{});assert.equal(r.status,404)}assert.equal((await send(e,'reservations')).body.length,1);const t=await send(e,'tasks','POST',taskData);assert.equal((await send(e,'tasks/'+t.body.id+'/extra','PATCH',{status:'Concluída'})).status,404);assert.equal((await send(e,'tasks')).body[0].status,'Pendente')});
test('substitution can be unassigned; deactivating auxiliary releases future lessons atomically',async()=>{const e=setup();const a=await send(e,'auxiliaries','POST',{name:'Auxiliar fictícia'});const sub=await send(e,'substitutions','POST',{date:'2099-10-05',start:'08:00',end:'08:45',class:'Turma fictícia',teacher:'Professor fictício'});assert.equal((await send(e,'substitutions/'+sub.body.id,'PATCH',{auxiliary:a.body.id})).status,200);assert.equal((await send(e,'substitutions/'+sub.body.id,'PATCH',{auxiliary:null})).status,200);assert.equal((await send(e,'substitutions')).body[0].auxiliary,null);await send(e,'substitutions/'+sub.body.id,'PATCH',{auxiliary:a.body.id});assert.equal((await send(e,'auxiliaries/'+a.body.id,'DELETE',{})).status,200);assert.equal((await send(e,'substitutions')).body[0].auxiliary,null);assert.equal((await send(e,'substitutions/'+sub.body.id,'PATCH',{auxiliary:a.body.id})).status,400)});
