import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const html=await readFile(new URL('../src/index.html',import.meta.url),'utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('});boot();','});');
function context(now){const Clock=now?class extends Date{constructor(...args){super(...(args.length?args:[now]))}}:Date;const c=vm.createContext({Date:Clock,Intl,setTimeout:()=>{},document:{addEventListener(){},querySelectorAll(){return []}},FormData,Object,String,Number});vm.runInContext(script,c);vm.runInContext("currentUser={email:'demo@prof.pmf.sc.gov.br',role:'direction'};users=[currentUser]",c);return c}
test('all available school pages render with empty database and preserve brand',()=>{const c=context();vm.runInContext('state.subs=[];state.aux=[];state.tasks=[];state.bookings=[];state.xerox=[];state.minutes=[];state.events=[]',c);for(const name of ['dashboard','substitutions','roomPage','tasksPage','xeroxPage','minutesPage','calendarPage'])assert.equal(typeof vm.runInContext(name+'()',c),'string');assert.match(html,/EBM Donícia Maria da Costa/);assert.match(html,/focus-visible/);assert.match(html,/role="alert"/);assert.match(html,/America\/Sao_Paulo/)});
test('stored names and reservation owner text are HTML-escaped',()=>{const c=context();vm.runInContext("state.aux=[{name:'<img src=x onerror=alert(1)>',weekly:0}];state.bookings=[{id:'1',space:'Biblioteca',date:iso,start:'09:00',end:'10:00',owner:'<img src=x>',purpose:'<script>bad</script>'}]",c);assert.equal(vm.runInContext('substitutions()',c).includes('<img'),false);assert.equal(vm.runInContext('roomPage()',c).includes('<img'),false)});
test('UI save sends versioned payloads for edit and state transitions',async()=>{const c=context();c.document.querySelector=()=>({disabled:false,isConnected:true});c.calls=[];vm.runInContext("api=async(...args)=>{calls.push(args);return {ok:true}};refresh=async()=>{};closeModal=()=>{};toast=()=>{};error=x=>{throw Error(x)};state.tasks=[{id:'task-1',version:3,ownerEmail:currentUser.email,title:'T',due:iso,restricted:false}];state.subs=[{id:'sub-1',version:2}];state.xerox=[{id:'xerox-1',version:4}];state.bookings=[{id:'booking-1',version:5}]",c);c.form={entries(){return [['title','T editada'],['due','2026-10-05'],['owner','demo@prof.pmf.sc.gov.br'],['visibility','Toda a equipe']]}};await vm.runInContext("save('edit-tasks',0,form)",c);assert.equal(c.calls[0][0],'tasks/task-1');assert.equal(c.calls[0][2].version,3);assert.equal(c.calls[0][2].restricted,false);c.form={entries(){return [['status','Concluída']]}};await vm.runInContext("save('task',0,form)",c);assert.equal(c.calls[1][2].version,3);c.form={entries(){return [['auxiliary','a-1']]}};await vm.runInContext("save('assign',0,form)",c);assert.equal(c.calls[2][2].version,2);c.form={entries(){return [['title','Material'],['copies','12'],['deadline','2026-10-05']]}};await vm.runInContext("save('revise-xerox',0,form)",c);assert.equal(c.calls[3][2].resubmit,true);assert.equal(c.calls[3][2].version,4);assert.equal(c.calls[3][2].copies,12)});
function modalContext(){const c=context();const nodes=new Map();function node(key){if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',disabled:false,isConnected:true,focus(){},append(){},classList:{remove(){}}});return nodes.get(key)}c.document.querySelector=node;c.document.createElement=()=>node('created');c.document.querySelectorAll=()=>[];c.nodes=nodes;vm.runInContext("state.tasks=[{id:'task-1',version:1,title:'Tarefa fictícia',due:iso,ownerEmail:currentUser.email,restricted:false}]",c);return c}
test('edit and returned xerox dialogs have meaningful titles, never undefined',()=>{const c=modalContext();vm.runInContext("modal('edit-tasks',0)",c);assert.match(c.nodes.get('#modalroot').innerHTML,/Editar tarefa/);assert.equal(c.nodes.get('#modalroot').innerHTML.includes('undefined'),false);vm.runInContext("state.xerox=[{id:'x',version:1,title:'Material',copies:10,deadline:iso}];modal('revise-xerox',0)",c);assert.match(c.nodes.get('#modalroot').innerHTML,/Ajustar e reenviar pedido/)});
test('pending save cannot be dismissed/replaced; refresh failure never masquerades as failed save',async()=>{const c=modalContext();let resolve;c.promise=new Promise(r=>resolve=r);c.form={entries(){return [['status','Concluída']]}};vm.runInContext("modal('task',0);api=()=>promise;refresh=async()=>{throw Error('offline')};toast=()=>{}",c);const pending=vm.runInContext("save('task',0,form)",c);const before=c.nodes.get('#modalroot').innerHTML;vm.runInContext("closeModal();modal('new-task')",c);assert.equal(c.nodes.get('#modalroot').innerHTML,before);resolve({ok:true});await pending;assert.equal(c.nodes.get('#modalroot').innerHTML,'');assert.match(c.nodes.get('#page').innerHTML,/alteração foi salva/);assert.equal(vm.runInContext('busy',c),false)});

test('school today and week respect Sunday/Monday boundary in São Paulo',()=>{const c=context('2026-10-05T01:00:00Z');assert.equal(vm.runInContext('iso',c),'2026-10-04');assert.equal(vm.runInContext('weekOf(iso)',c),'2026-09-28');const monday=context('2026-10-05T03:01:00Z');assert.equal(vm.runInContext('iso',monday),'2026-10-05');assert.equal(vm.runInContext('weekOf(iso)',monday),'2026-10-05')});
