import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:integer('value').notNull()});
// SQL migration is authoritative for CHECK constraints and atomic triggers.
export const users=sqliteTable('users',{email:text('email').primaryKey(),name:text('name').notNull(),role:text('role',{enum:['direction','teacher']}).notNull(),active:integer('active').notNull().default(1)});
export const reservations=sqliteTable('reservations',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),space:text('space').notNull(),date:text('date').notNull(),start:text('start').notNull(),end:text('end').notNull(),owner:text('owner').notNull().references(()=>users.email),purpose:text('purpose').notNull(),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index('reservations_schedule').on(t.space,t.date,t.start,t.end)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),title:text('title').notNull(),owner:text('owner').notNull().references(()=>users.email),due:text('due').notNull(),status:text('status',{enum:['Pendente','Em andamento','Concluída']}).notNull().default('Pendente'),restricted:integer('restricted').notNull().default(0),creator:text('creator').notNull().references(()=>users.email),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)});
export const auxiliaries=sqliteTable('auxiliaries',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),name:text('name').notNull(),active:integer('active').notNull().default(1)});
export const substitutions=sqliteTable('substitutions',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),date:text('date').notNull(),week:text('week').notNull(),start:text('start').notNull(),end:text('end').notNull(),class:text('class').notNull(),teacher:text('teacher').notNull(),auxiliary:text('auxiliary').references(()=>auxiliaries.id),completed:integer('completed').notNull().default(0),creator:text('creator').notNull().references(()=>users.email)},t=>[index('substitutions_week').on(t.auxiliary,t.week)]);
export const xerox=sqliteTable('xerox',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),title:text('title').notNull(),copies:integer('copies').notNull(),deadline:text('deadline').notNull(),requester:text('requester').notNull().references(()=>users.email),status:text('status').notNull().default('Aguardando aprovação')});
export const minutes=sqliteTable('minutes',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),title:text('title').notNull(),date:text('date').notNull(),participants:text('participants').notNull(),decisions:text('decisions').notNull(),creator:text('creator').notNull().references(()=>users.email)});
export const events=sqliteTable('events',{id:text('id').primaryKey(),version:integer('version').notNull().default(1),title:text('title').notNull(),date:text('date').notNull(),type:text('type').notNull(),creator:text('creator').notNull().references(()=>users.email)});

export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull().references(()=>users.email),action:text('action').notNull(),target:text('target').notNull(),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)});
export const fixedOccupancy=sqliteTable('fixed_occupancy',{id:text('id').primaryKey(),space:text('space').notNull(),weekday:integer('weekday').notNull(),start:text('start').notNull(),end:text('end').notNull(),fromDate:text('from_date').notNull(),toDate:text('to_date').notNull(),purpose:text('purpose').notNull(),creator:text('creator').notNull().references(()=>users.email),version:integer('version').notNull().default(1)});

export const teacherDirectory=sqliteTable('teacher_directory',{id:integer('id').primaryKey(),names:text('names').notNull(),sourceVersion:text('source_version').notNull(),fetchedAt:text('fetched_at').notNull()});
